### ISSUE TITLE
Schematics support ?

### ISSUE THREAD

**Issue by Jordan-Hall** [alosaur/angular_deno#1]
Hey,

Does this package support Angular Schematics? Was thinking of porting a CLI over using Angular Schematic to generate alosaur
 code

**Comment by irustm** [comment]
This package is only renderer angular. And so far only experimental.

I am thinking about moving the functionality of the angular schematics cli completely to Deno.
https://github.com/alosaur/alosaur-schematics/issues/6

**Comment by Jordan-Hall** [comment]
Amazing news. I'll close this one and look at the other repo. Love alosaur
/
